//
//  Constants.m
//  FlameTouch
//
//  Created by Tom Insam on 26/06/2009.
//  Copyright 2009 jerakeen.org. All rights reserved.
//

#import "Utility.h"

#include <netinet/in.h>
#include <arpa/inet.h>


@implementation Utility

@synthesize serviceNames;

static Utility* sharedConstantsInstance = nil;
+(Utility*)sharedInstance {
  if (!sharedConstantsInstance) {
    sharedConstantsInstance = [[Utility alloc] init];
  }
  return sharedConstantsInstance;
}

-(id)init {
  self = [super init];
  
  // this list autp-generated from http://www.dns-sd.org/ServiceTypes.html
  // using the ruby script 'service_list_builder.rb'
  self.serviceNames = [NSDictionary dictionaryWithObjectsAndKeys:
                       @"1Password Password Manager data sharing and synchronization protocol", @"_1password._tcp.",
                       @"Applied Biosystems Universal Instrument Framework", @"_abi-instrument._tcp.",
                       @"FTK2 Database Discovery Service", @"_accessdata-f2d._tcp.",
                       @"FTK2 Backend Processing Agent Service", @"_accessdata-f2w._tcp.",
                       @"Strix Systems 5S/AccessOne protocol", @"_accessone._tcp.",
                       @"MYOB AccountEdge", @"_accountedge._tcp.",
                       @"Adobe Acrobat", @"_acrobatsrv._tcp.",
                       @"ActionItems", @"_actionitems._tcp.",
                       @"Active Storage Proprietary Device Management Protocol", @"_activeraid._tcp.",
                       @"Encrypted transport of Active Storage Proprietary Device Management Protocol", @"_activeraid-ssl._tcp.",
                       @"Address-O-Matic", @"_addressbook._tcp.",
                       @"Adobe Version Cue", @"_adobe-vc._tcp.",
                       @"Automatic Disk Discovery", @"_adisk._tcp.",
                       @"ADPRO Security Device Setup", @"_adpro-setup._tcp.",
                       @"Apple Application Engineering Services", @"_aecoretech._tcp.",
                       @"Aeroflex instrumentation and software", @"_aeroflex._tcp.",
                       @"Apple File Sharing", @"_afpovertcp._tcp.",
                       @"AirPort Base Station", @"_airport._tcp.",
                       @"AirProjector", @"_airprojector._tcp.",
                       @"Animo License Manager", @"_animolmd._tcp.",
                       @"Animo Batch Server", @"_animobserver._tcp.",
                       @"Appelezvous", @"_appelezvous._tcp.",
                       @"Apple Audio Units", @"_apple-ausend._tcp.",
                       @"Apple MIDI", @"_apple-midi._tcp.",
                       @"Apple Password Server", @"_apple-sasl._tcp.",
                       @"Apple Remote Debug Services (OpenGL Profiler)", @"_applerdbg._tcp.",
                       @"Apple TV", @"_appletv._tcp.",
                       @"Apple TV discovery of iTunes", @"_appletv-itunes._tcp.",
                       @"Apple TV Pairing", @"_appletv-pair._tcp.",
                       @"AquaMon", @"_aquamon._tcp.",
                       @"Apple Software Restore", @"_asr._tcp.",
                       @"Asterisk Caller-ID Notification Service", @"_astnotify._tcp.",
                       @"Astralite", @"_astralite._tcp.",
                       @"address-o-sync", @"_async._tcp.",
                       @"Allen Vanguard Hardware Service", @"_av._tcp.",
                       @"Axis Video Cameras", @"_axis-video._tcp.",
                       @"Authentication Service", @"_auth._tcp.",
                       @"3M Unitek Digital Orthodontic System", @"_b3d-convince._tcp.",
                       @"BibDesk Sharing", @"_bdsk._tcp.",
                       @"BeatPack Synchronization Server for BeatMaker", @"_beatpack._tcp.",
                       @"Xgrid Technology Preview", @"_beep._tcp.",
                       @"BuildForge Agent", @"_bfagent._tcp.",
                       @"Big Bang Chess", @"_bigbangchess._tcp.",
                       @"Big Bang Mancala", @"_bigbangmancala._tcp.",
                       @"BitTorrent Zeroconf Peer Discovery Protocol", @"_bittorrent._tcp.",
                       @"Little Black Book Information Exchange Protocol", @"_blackbook._tcp.",
                       @"BlueVertise Network Protocol (BNP)", @"_bluevertise._tcp.",
                       @"Bookworm Client Discovery", @"_bookworm._tcp.",
                       @"Bootstrap Protocol Server", @"_bootps._tcp.",
                       @"Proprietary", @"_boundaryscan._tcp.",
                       @"Bag Of Unusual Strategy Games", @"_bousg._tcp.",
                       @"RFID Reader Basic Reader Interface", @"_bri._tcp.",
                       @"Backup Simplicity", @"_bsqdea._tcp.",
                       @"BusySync Calendar Synchronization Protocol", @"_busycal._tcp.",
                       @"CalTalk", @"_caltalk._tcp.",
                       @"Card Send Protocol", @"_cardsend._tcp.",
                       @"The Cheat", @"_cheat._tcp.",
                       @"Project Gridlock", @"_chess._tcp.",
                       @"Fluid Theme Server", @"_chfts._tcp.",
                       @"The CHILI Radiology System", @"_chili._tcp.",
                       @"Clipboard Sharing", @"_clipboard._tcp.",
                       @"Clique Link-Local Multicast Chat Room", @"_clique._tcp.",
                       @"Oracle CLS Cluster Topology Service", @"_clscts._tcp.",
                       @"Published Collection Object", @"_collection._tcp.",
                       @"Now Contact", @"_contactserver._tcp.",
                       @"Corroboree Server", @"_corroboree._tcp.",
                       @"NoteBook 2", @"_cpnotebook2._tcp.",
                       @"CVS PServer", @"_cvspserver._tcp.",
                       @"CodeWarrior HTI Xscale PowerTAP", @"_cw-codetap._tcp.",
                       @"CodeWarrior HTI DPI PowerTAP", @"_cw-dpitap._tcp.",
                       @"CodeWarrior HTI OnCE PowerTAP", @"_cw-oncetap._tcp.",
                       @"CodeWarrior HTI COP PowerTAP", @"_cw-powertap._tcp.",
                       @"CyTV", @"_cytv._tcp.",
                       @"Digital Audio Access Protocol (iTunes)", @"_daap._tcp.",
                       @"Digital Audio Control Protocol (iTunes)", @"_dacp._tcp.",
                       @"Device Info", @"_device-info._tcp.",
                       @"EyeHome", @"_difi._tcp.",
                       @"Distributed Compiler", @"_distcc._tcp.",
                       @"Ditrios SOA Framework Protocol", @"_ditrios._tcp.",
                       @"Dive Log Data Sharing and Synchronization Protocol", @"_divelogsync._tcp.",
                       @"Local Area Dynamic Time Synchronisation Protocol", @"_dltimesync._tcp.",
                       @"DNS Long-Lived Queries", @"_dns-llq._tcp.",
                       @"DNS Service Discovery", @"_dns-sd._tcp.",
                       @"DNS Dynamic Update Service", @"_dns-update._tcp.",
                       @"Domain Name Server", @"_domain._tcp.",
                       @"Vortimac Dossier Protocol", @"_dossier._tcp.",
                       @"Digital Photo Access Protocol (iPhoto)", @"_dpap._tcp.",
                       @"DropCopy", @"_dropcopy._tcp.",
                       @"Data Synchronization Protocol for Discovery Software products", @"_dsl-sync._tcp.",
                       @"Desktop Transporter Remote Desktop Protocol", @"_dtrmtdesktop._tcp.",
                       @"DVB Service Discovery", @"_dvbservdsc._tcp.",
                       @"Earphoria", @"_earphoria._tcp.",
                       @"ebXML Messaging", @"_ebms._tcp.",
                       @"Northrup Grumman/Mission Systems/ESL Data Flow Protocol", @"_ecms._tcp.",
                       @"ebXML Registry", @"_ebreg._tcp.",
                       @"Net Monitor Anti-Piracy Service", @"_ecbyesfsgksc._tcp.",
                       @"LaCie Ethernet Disk Configuration Protocol", @"_edcp._tcp.",
                       @"Interactive Room Software Infrastructure (Event Sharing)", @"_eheap._tcp.",
                       @"DataEnvoy", @"_embrace._tcp.",
                       @"Remote AppleEvents", @"_eppc._tcp.",
                       @"Extensis Server Protocol", @"_esp._tcp.",
                       @"Now Up-to-Date", @"_eventserver._tcp.",
                       @"Synchronization Protocol for Ilium Software's eWallet", @"_ewalletsync._tcp.",
                       @"Example Service Type", @"_example._tcp.",
                       @"Exbiblio Cascading Service Protocol", @"_exb._tcp.",
                       @"Remote Process Execution", @"_exec._tcp.",
                       @"Extensis Serial Number", @"_extensissn._tcp.",
                       @"EyeTV Sharing", @"_eyetvsn._tcp.",
                       @"FaceSpan", @"_facespan._tcp.",
                       @"Fairview Device Identification", @"_fairview._tcp.",
                       @"FAXstf", @"_faxstfx._tcp.",
                       @"NetNewsWire 2.0", @"_feed-sharing._tcp.",
                       @"Fish", @"_fish._tcp.",
                       @"Financial Information Exchange (FIX) Protocol", @"_fix._tcp.",
                       @"Fjork", @"_fjork._tcp.",
                       @"FilmLight Cluster Power Control Service", @"_fl-purr._tcp.",
                       @"FileMaker Pro", @"_fmpro-internal._tcp.",
                       @"FileMaker Server Administration Communication Service", @"_fmserver-admin._tcp.",
                       @"FontAgent Pro", @"_fontagentnode._tcp.",
                       @"FoxTrot Professional Search Discovery Service", @"_foxtrot-start._tcp.",
                       @"FreeHand MusicPad Pro Interface Protocol", @"_freehand._tcp.",
                       @"File Transfer", @"_ftp._tcp.",
                       @"Crocodile FTP Server", @"_ftpcroco._tcp.",
                       @"Fairview Certificate", @"_fv-cert._tcp.",
                       @"Fairview Key", @"_fv-key._tcp.",
                       @"Fairview Time/Date", @"_fv-time._tcp.",
                       @"Frog Navigation Systems", @"_frog._tcp.",
                       @"SnapMail", @"_gbs-smp._tcp.",
                       @"SnapTalk", @"_gbs-stp._tcp.",
                       @"G-Force Control via SoundSpectrum's SSMP TCP Protocol", @"_gforce-ssmp._tcp.",
                       @"GlassPad Data Exchange Protocol", @"_glasspad._tcp.",
                       @"GlassPadServer Data Exchange Protocol", @"_glasspadserver._tcp.",
                       @"OpenGL Driver Monitor", @"_glrdrvmon._tcp.",
                       @"Grid Plug and Play", @"_gpnp._tcp.",
                       @"Roxio ToastAnywhere(tm) Recorder Sharing", @"_grillezvous._tcp.",
                       @"Growl", @"_growl._tcp.",
                       @"Special service type for resolving by GUID (Globally Unique Identifier)", @"_guid._tcp.",
                       @"H.323 Real-time audio, video and data communication call setup protocol", @"_h323._tcp.",
                       @"MultiUser Helix Server", @"_helix._tcp.",
                       @"Home Media Control Protocol", @"_hmcp._tcp.",
                       @"World Wide Web HTML-over-HTTP", @"_http._tcp.",
                       @"HTTP over SSL/TLS", @"_https._tcp.",
                       @"iDo Technology Home Automation Protocol", @"_homeauto._tcp.",
                       @"Honeywell Video Systems", @"_honeywell-vid._tcp.",
                       @"Hotwayd", @"_hotwayd._tcp.",
                       @"Howdy messaging and notification protocol", @"_howdy._tcp.",
                       @"HP Remote Build System for Linux-based Systems", @"_hpr-bldlnx._tcp.",
                       @"HP Remote Build System for Microsoft Windows Systems", @"_hpr-bldwin._tcp.",
                       @"Identifies systems that house databases for the Remote Build System and Remote Test System", @"_hpr-db._tcp.",
                       @"HP Remote Repository for Build and Test Results", @"_hpr-rep._tcp.",
                       @"HP Remote System that houses compilers and tools for Linux-based Systems", @"_hpr-toollnx._tcp.",
                       @"HP Remote System that houses compilers and tools for Microsoft Windows Systems", @"_hpr-toolwin._tcp.",
                       @"HP Remote Test System for Linux-based Systems", @"_hpr-tstlnx._tcp.",
                       @"HP Remote Test System for Microsoft Windows Systems", @"_hpr-tstwin._tcp.",
                       @"Hobbyist Software Off Discovery", @"_hs-off._tcp.",
                       @"SubEthaEdit", @"_hydra._tcp.",
                       @"Inter Asterisk eXchange, ease-of-use NAT friendly open VoIP protocol", @"_iax._tcp.",
                       @"iBiz Server", @"_ibiz._tcp.",
                       @"Image Capture Networking", @"_ica-networking._tcp.",
                       @"Northrup Grumman/TASC/ICAN Protocol", @"_ican._tcp.",
                       @"iChalk", @"_ichalkboard._tcp.",
                       @"iChat 1.0", @"_ichat._tcp.",
                       @"iConquer", @"_iconquer._tcp.",
                       @"Generic Data Acquisition and Control Protocol", @"_idata._tcp.",
                       @"SplashID Synchronization Service", @"_idsync._tcp.",
                       @"Published iFolder", @"_ifolder._tcp.",
                       @"Idle Hands iHouse Protocol", @"_ihouse._tcp.",
                       @"Instant Interactive Drills", @"_ii-drills._tcp.",
                       @"Instant Interactive Konane", @"_ii-konane._tcp.",
                       @"iLynX", @"_ilynx._tcp.",
                       @"Internet Message Access Protocol", @"_imap._tcp.",
                       @"iMidi", @"_imidi._tcp.",
                       @"Inova Solutions OnTrack Display Protocol", @"_inova-ontrack._tcp.",
                       @"Intermec Device Configuration Web Services", @"_idcws._tcp.",
                       @"IP Broadcaster", @"_ipbroadcaster._tcp.",
                       @"IPP (Internet Printing Protocol)", @"_ipp._tcp.",
                       @"IP Speaker Control Protocol", @"_ipspeaker._tcp.",
                       @"Intego Remote Management Console", @"_irmc._tcp.",
                       @"Internet Small Computer Systems Interface (iSCSI)", @"_iscsi._tcp.",
                       @"iSparx", @"_isparx._tcp.",
                       @"iSpQ VideoChat", @"_ispq-vc._tcp.",
                       @"iShare", @"_ishare._tcp.",
                       @"iSticky", @"_isticky._tcp.",
                       @"iStorm", @"_istorm._tcp.",
                       @"iTunes Socket Remote Control", @"_itsrc._tcp.",
                       @"iWork Server", @"_iwork._tcp.",
                       @"Northrup Grumman/TASC/JCAN Protocol", @"_jcan._tcp.",
                       @"Jedit X", @"_jeditx._tcp.",
                       @"Jini Service Discovery", @"_jini._tcp.",
                       @"Proprietary", @"_jtag._tcp.",
                       @"Kerberos", @"_kerberos._tcp.",
                       @"Kerberos Administration", @"_kerberos-adm._tcp.",
                       @"Kabira Transaction Platform", @"_ktp._tcp.",
                       @"Lan2P Peer-to-Peer Network Protocol", @"_lan2p._tcp.",
                       @"Gawker", @"_lapse._tcp.",
                       @"LANrev Agent", @"_lanrevagent._tcp.",
                       @"LANrev Server", @"_lanrevserver._tcp.",
                       @"Lightweight Directory Access Protocol", @"_ldap._tcp.",
                       @"Lexicon Vocabulary Sharing", @"_lexicon._tcp.",
                       @"Liaison", @"_liaison._tcp.",
                       @"Delicious Library 2 Collection Data Sharing Protocol", @"_library._tcp.",
                       @"RFID reader Low Level Reader Protocol", @"_llrp._tcp.",
                       @"RFID reader Low Level Reader Protocol over SSL/TLS", @"_llrp-secure._tcp.",
                       @"Gobby", @"_lobby._tcp.",
                       @"Logic Pro Distributed Audio", @"_logicnode._tcp.",
                       @"Remote Login a la Telnet", @"_login._tcp.",
                       @"LonTalk over IP (ANSI 852)", @"_lontalk._tcp.",
                       @"Echelon LNS Remote Client", @"_lonworks._tcp.",
                       @"Linksys One Application Server API", @"_lsys-appserver._tcp.",
                       @"Linksys One Camera API", @"_lsys-camera._tcp.",
                       @"LinkSys EZ Configuration", @"_lsys-ezcfg._tcp.",
                       @"LinkSys Operations, Administration, Management, and Provisioning", @"_lsys-oamp._tcp.",
                       @"Lux Solis Data Transport Protocol", @"_lux-dtp._tcp.",
                       @"LXI", @"_lxi._tcp.",
                       @"iPod Lyrics Service", @"_lyrics._tcp.",
                       @"MacFOH", @"_macfoh._tcp.",
                       @"MacFOH admin services", @"_macfoh-admin._tcp.",
                       @"MacFOH audio stream", @"_macfoh-audio._tcp.",
                       @"MacFOH show control events", @"_macfoh-events._tcp.",
                       @"MacFOH realtime data", @"_macfoh-data._tcp.",
                       @"MacFOH database", @"_macfoh-db._tcp.",
                       @"MacFOH Remote", @"_macfoh-remote._tcp.",
                       @"Mac Minder", @"_macminder._tcp.",
                       @"Maestro Music Sharing Service", @"_maestro._tcp.",
                       @"Magic Dice Game Protocol", @"_magicdice._tcp.",
                       @"Mandos Password Server", @"_mandos._tcp.",
                       @"MediaBroker++ Consumer", @"_mbconsumer._tcp.",
                       @"MediaBroker++ Producer", @"_mbproducer._tcp.",
                       @"MediaBroker++ Server", @"_mbserver._tcp.",
                       @"MediaCentral", @"_mcrcp._tcp.",
                       @"Mes Amis", @"_mesamis._tcp.",
                       @"Mimer SQL Engine", @"_mimer._tcp.",
                       @"Mental Ray for Maya", @"_mi-raysat._tcp.",
                       @"modo LAN Services", @"_modolansrv._tcp.",
                       @"SplashMoney Synchronization Service", @"_moneysync._tcp.",
                       @"MoneyWorks Gold and MoneyWorks Datacentre network service", @"_moneyworks._tcp.",
                       @"Bonjour Mood Ring tutorial program", @"_moodring._tcp.",
                       @"Mother script server protocol", @"_mother._tcp.",
                       @"MP3 Sushi", @"_mp3sushi._tcp.",
                       @"IBM MQ Telemetry Transport Broker", @"_mqtt._tcp.",
                       @"Martian SlingShot", @"_mslingshot._tcp.",
                       @"MySync Protocol", @"_mysync._tcp.",
                       @"MenuTunes Sharing", @"_mttp._tcp.",
                       @"MatrixStore", @"_mxs._tcp.",
                       @"Network Clipboard Broadcasts", @"_ncbroadcast._tcp.",
                       @"Network Clipboard Direct Transfers", @"_ncdirect._tcp.",
                       @"Network Clipboard Sync Server", @"_ncsyncserver._tcp.",
                       @"NeoRiders Client Discovery Protocol", @"_neoriders._tcp.",
                       @"Apple Remote Desktop", @"_net-assistant._tcp.",
                       @"Vesa Net2Display", @"_net2display._tcp.",
                       @"NetRestore", @"_netrestore._tcp.",
                       @"Escale", @"_newton-dock._tcp.",
                       @"Network File System - Sun Microsystems", @"_nfs._tcp.",
                       @"DO over NSSocketPort", @"_nssocketport._tcp.",
                       @"American Dynamics Intellex Archive Management Service", @"_ntlx-arch._tcp.",
                       @"American Dynamics Intellex Enterprise Management Service", @"_ntlx-ent._tcp.",
                       @"American Dynamics Intellex Video Service", @"_ntlx-video._tcp.",
                       @"Network Time Protocol", @"_ntp._tcp.",
                       @"Tenasys", @"_ntx._tcp.",
                       @"Observations Framework", @"_obf._tcp.",
                       @"Means for clients to locate servers in an Objective (http://www.objective.com) instance.", @"_objective._tcp.",
                       @"Oce Common Exchange Protocol", @"_oce._tcp.",
                       @"OD4Contact", @"_odabsharing._tcp.",
                       @"Optical Disk Sharing", @"_odisk._tcp.",
                       @"OmniFocus setting configuration", @"_ofocus-conf._tcp.",
                       @"OmniFocus document synchronization", @"_ofocus-sync._tcp.",
                       @"One Laptop per Child activity", @"_olpc-activity1._tcp.",
                       @"OmniWeb", @"_omni-bookmark._tcp.",
                       @"OpenBase SQL", @"_openbase._tcp.",
                       @"Conferencing Protocol", @"_opencu._tcp.",
                       @"oprofile server protocol", @"_oprofile._tcp.",
                       @"Open Sound Control Interface Transfer", @"_oscit._tcp.",
                       @"ObjectVideo OV Ready Protocol", @"_ovready._tcp.",
                       @"OWFS (1-wire file system) web server", @"_owhttpd._tcp.",
                       @"OWFS (1-wire file system) server", @"_owserver._tcp.",
                       @"Remote Parental Controls", @"_parentcontrol._tcp.",
                       @"PasswordWallet Data Synchronization Protocol", @"_passwordwallet._tcp.",
                       @"Mac OS X Podcast Producer Server", @"_pcast._tcp.",
                       @"Peer-to-Peer Chat (Sample Java Bonjour application)", @"_p2pchat._tcp.",
                       @"PhoneValet Anywhere", @"_parliant._tcp.",
                       @"Printer Page Description Language Data Stream (vendor-specific)", @"_pdl-datastream._tcp.",
                       @"Horowitz Key Protocol (HKP)", @"_pgpkey-hkp._tcp.",
                       @"PGP Keyserver using HTTP/1.1", @"_pgpkey-https._tcp.",
                       @"PGP Keyserver using HTTPS", @"_pgpkey-https._tcp.",
                       @"PGP Keyserver using LDAP", @"_pgpkey-ldap._tcp.",
                       @"PGP Key submission using SMTP", @"_pgpkey-mailto._tcp.",
                       @"Photo Parata Event Photography Software", @"_photoparata._tcp.",
                       @"Pictua Intercommunication Protocol", @"_pictua._tcp.",
                       @"pieSync Computer to Computer Synchronization", @"_piesync._tcp.",
                       @"Pedestal Interface Unit by RPM-PSI", @"_piu._tcp.",
                       @"Parallel OperatiOn and Control Heuristic (Pooch)", @"_poch._tcp.",
                       @"Communication channel for \"Poke Eye\" Elgato EyeTV remote controller", @"_pokeeye._tcp.",
                       @"Post Office Protocol - Version 3", @"_pop3._tcp.",
                       @"PostgreSQL Server", @"_postgresql._tcp.",
                       @"PowerEasy ERP", @"_powereasy-erp._tcp.",
                       @"PowerEasy Point of Sale", @"_powereasy-pos._tcp.",
                       @"Piano Player Remote Control", @"_pplayer-ctrl._tcp.",
                       @"Peer-to-peer messaging / Link-Local Messaging", @"_presence._tcp.",
                       @"Retrieve a description of a device's print capabilities", @"_print-caps._tcp.",
                       @"Spooler (more commonly known as \"LPR printing\" or \"LPD printing\")", @"_printer._tcp.",
                       @"Profile for Mac medical practice management software", @"_profilemac._tcp.",
                       @"Prolog", @"_prolog._tcp.",
                       @"Physical Security Interoperability Alliance Protocol", @"_psia._tcp.",
                       @"PTNetPro Service", @"_ptnetprosrv2._tcp.",
                       @"Picture Transfer Protocol", @"_ptp._tcp.",
                       @"PTP Initiation Request Protocol", @"_ptp-req._tcp.",
                       @"QBox Appliance Locator", @"_qbox._tcp.",
                       @"QuickTime Transfer Protocol", @"_qttp._tcp.",
                       @"Quinn Game Server", @"_quinn._tcp.",
                       @"Rakket Client Protocol", @"_rakket._tcp.",
                       @"RadioTAG: Event tagging for radio services", @"_radiotag._tcp.",
                       @"RadioVIS: Visualisation for radio services", @"_radiovis._tcp.",
                       @"RadioEPG:?Electronic Programme Guide for?radio services", @"_radioepg._tcp.",
                       @"Remote Audio Output Protocol (AirTunes)", @"_raop._tcp.",
                       @"RBR Instrument Communication", @"_rbr._tcp.",
                       @"PowerCard", @"_rce._tcp.",
                       @"Windows Remote Desktop Protocol", @"_rdp._tcp.",
                       @"RealPlayer Shared Favorites", @"_realplayfavs._tcp.",
                       @"Recipe Sharing Protocol", @"_recipe._tcp.",
                       @"LaCie Remote Burn", @"_remoteburn._tcp.",
                       @"ARTvps RenderDrive/PURE Renderer Protocol", @"_renderpipe._tcp.",
                       @"RendezvousPong", @"_rendezvouspong._tcp.",
                       @"Community Service", @"_resacommunity._tcp.",
                       @"RESOL VBus", @"_resol-vbus._tcp.",
                       @"Retrospect backup and restore service", @"_retrospect._tcp.",
                       @"Remote Frame Buffer (used by VNC)", @"_rfb._tcp.",
                       @"Remote Frame Buffer Client (Used by VNC viewers in listen-mode)", @"_rfbc._tcp.",
                       @"RFID Reader Mach1(tm) Protocol", @"_rfid._tcp.",
                       @"Remote I/O USB Printer Protocol", @"_riousbprint._tcp.",
                       @"Roku Control Protocol", @"_roku-rcp._tcp.",
                       @"RemoteQuickLaunch", @"_rql._tcp.",
                       @"Remote System Management Protocol (Server Instance)", @"_rsmp-server._tcp.",
                       @"Rsync", @"_rsync._tcp.",
                       @"Real Time Streaming Protocol", @"_rtsp._tcp.",
                       @"RubyGems GemServer", @"_rubygems._tcp.",
                       @"Safari Menu", @"_safarimenu._tcp.",
                       @"Salling Clicker Sharing", @"_sallingbridge._tcp.",
                       @"Salling Clicker Service", @"_sallingclicker._tcp.",
                       @"Salutafugi Peer-To-Peer Java Message Service Implementation", @"_salutafugijms._tcp.",
                       @"Sandvox", @"_sandvox._tcp.",
                       @"Bonjour Scanning", @"_scanner._tcp.",
                       @"Schick", @"_schick._tcp.",
                       @"Scone", @"_scone._tcp.",
                       @"IEEE 488.2 (SCPI) Socket", @"_scpi-raw._tcp.",
                       @"IEEE 488.2 (SCPI) Telnet", @"_scpi-telnet._tcp.",
                       @"Speed Download", @"_sdsharing._tcp.",
                       @"SubEthaEdit 2", @"_see._tcp.",
                       @"seeCard", @"_seeCard._tcp.",
                       @"Senteo Assessment Software Protocol", @"_senteo-http._tcp.",
                       @"Sentillion Vault System", @"_sentillion-vlc._tcp.",
                       @"Sentillion Vault Systems Cluster", @"_sentillion-vlt._tcp.",
                       @"serendiPd Shared Patches for Pure Data", @"_serendipd._tcp.",
                       @"ServerEye AgentContainer Communication Protocol", @"_servereye._tcp.",
                       @"Mac OS X Server Admin", @"_servermgr._tcp.",
                       @"DNS Service Discovery", @"_services._tcp.",
                       @"Session File Sharing", @"_sessionfs._tcp.",
                       @"Secure File Transfer Protocol over SSH", @"_sftp-ssh._tcp.",
                       @"like exec, but automatic authentication is performed as for login server.", @"_shell._tcp.",
                       @"Swift Office Ships", @"_shipsgm._tcp.",
                       @"Swift Office Ships", @"_shipsinvit._tcp.",
                       @"SplashShopper Synchronization Service", @"_shoppersync._tcp.",
                       @"Nicecast", @"_shoutcast._tcp.",
                       @"Session Initiation Protocol, signalling protocol for VoIP", @"_sip._tcp.",
                       @"Session Initiation Protocol Uniform Resource Identifier", @"_sipuri._tcp.",
                       @"Sirona Xray Protocol", @"_sironaxray._tcp.",
                       @"Skype", @"_skype._tcp.",
                       @"Sleep Proxy Server", @"_sleep-proxy._tcp.",
                       @"SliMP3 Server Command-Line Interface", @"_slimcli._tcp.",
                       @"SliMP3 Server Web Interface", @"_slimhttp._tcp.",
                       @"Server Message Block over TCP/IP", @"_smb._tcp.",
                       @"Simple Object Access Protocol", @"_soap._tcp.",
                       @"Simple Object eXchange", @"_sox._tcp.",
                       @"sPearCat Host Discovery", @"_spearcat._tcp.",
                       @"Shared Clipboard Protocol", @"_spike._tcp.",
                       @"Spin Crisis", @"_spincrisis._tcp.",
                       @"launchTunes", @"_spl-itunes._tcp.",
                       @"netTunes", @"_spr-itunes._tcp.",
                       @"SplashData Synchronization Service", @"_splashsync._tcp.",
                       @"SSH Remote Login Protocol", @"_ssh._tcp.",
                       @"Screen Sharing", @"_ssscreenshare._tcp.",
                       @"Strateges", @"_strateges._tcp.",
                       @"Sun Grid Engine (Execution Host)", @"_sge-exec._tcp.",
                       @"Sun Grid Engine (Master)", @"_sge-qmaster._tcp.",
                       @"SousChef Recipe Sharing Protocol", @"_souschef._tcp.",
                       @"SPARQL Protocol and RDF Query Language", @"_sparql._tcp.",
                       @"Lexcycle Stanza service for discovering shared books", @"_stanza._tcp.",
                       @"Sticky Notes", @"_stickynotes._tcp.",
                       @"Message Submission", @"_submission._tcp.",
                       @"Supple Service protocol", @"_supple._tcp.",
                       @"Surveillus Networks Discovery Protocol", @"_surveillus._tcp.",
                       @"Subversion", @"_svn._tcp.",
                       @"Signwave Card Sharing Protocol", @"_swcards._tcp.",
                       @"Wireless home control remote control protocol", @"_switcher._tcp.",
                       @"Swordfish Protocol for Input/Output", @"_swordfish._tcp.",
                       @"Synchronize! Pro X", @"_sxqdea._tcp.",
                       @"Sybase Server", @"_sybase-tds._tcp.",
                       @"Syncopation Synchronization Protocol by Sonzea", @"_syncopation._tcp.",
                       @"Synchronize! X Plus 2.0", @"_syncqdea._tcp.",
                       @"Data Transmission and Synchronization", @"_taccounting._tcp.",
                       @"Tapinoma Easycontact receiver", @"_tapinoma-ecs._tcp.",
                       @"Task Coach Two-way Synchronization Protocol for iPhone", @"_taskcoachsync._tcp.",
                       @"tbricks internal protocol", @"_tbricks._tcp.",
                       @"Time Code", @"_tcode._tcp.",
                       @"Tracking Control Unit by RPM-PSI", @"_tcu._tcp.",
                       @"ARTIS Team Task", @"_teamlist._tcp.",
                       @"teleport", @"_teleport._tcp.",
                       @"Telnet", @"_telnet._tcp.",
                       @"Terascala Maintenance Protocol", @"_tera-mp._tcp.",
                       @"ThinkFlood RedEye IR bridge", @"_tf-redeye._tcp.",
                       @"Trivial File Transfer", @"_tftp._tcp.",
                       @"TI Connect Manager Discovery Service", @"_ticonnectmgr._tcp.",
                       @"Timbuktu", @"_timbuktu._tcp.",
                       @"TI Navigator Hub 1.0 Discovery Service", @"_tinavigator._tcp.",
                       @"TiVo Home Media Engine Protocol", @"_tivo-hme._tcp.",
                       @"TiVo Music Protocol", @"_tivo-music._tcp.",
                       @"TiVo Photos Protocol", @"_tivo-photos._tcp.",
                       @"TiVo Remote Protocol", @"_tivo-remote._tcp.",
                       @"TiVo Videos Protocol", @"_tivo-videos._tcp.",
                       @"Tomboy", @"_tomboy._tcp.",
                       @"ToothPics Dental Office Support Server", @"_toothpicserver._tcp.",
                       @"iPhone and iPod touch Remote Controllable", @"_touch-able._tcp.",
                       @"iPhone and iPod touch Remote Pairing", @"_touch-remote._tcp.",
                       @"Tryst", @"_tryst._tcp.",
                       @"TechTool Pro 4 Anti-Piracy Service", @"_ttp4daemon._tcp.",
                       @"Tunage Media Control Service", @"_tunage._tcp.",
                       @"TuneRanger", @"_tuneranger._tcp.",
                       @"Ubertragen", @"_ubertragen._tcp.",
                       @"Universal Description, Discovery and Integration", @"_uddi._tcp.",
                       @"Universal Description, Discovery and Integration Inquiry", @"_uddi-inq._tcp.",
                       @"Universal Description, Discovery and Integration Publishing", @"_uddi-pub._tcp.",
                       @"Universal Description, Discovery and Integration Subscription", @"_uddi-sub._tcp.",
                       @"Universal Description, Discovery and Integration Security", @"_uddi-sec._tcp.",
                       @"Universal Plug and Play", @"_upnp._tcp.",
                       @"Universal Switching Corporation products", @"_uswi._tcp.",
                       @"uTest", @"_utest._tcp.",
                       @"American Dynamics VideoEdge Decoder Control Service", @"_ve-decoder._tcp.",
                       @"American Dynamics VideoEdge Encoder Control Service", @"_ve-encoder._tcp.",
                       @"American Dynamics VideoEdge Recorder Control Service", @"_ve-recorder._tcp.",
                       @"visel Q-System services", @"_visel._tcp.",
                       @"Volley", @"_volley._tcp.",
                       @"Virtual Object System (using VOP/TCP)", @"_vos._tcp.",
                       @"VueProRenderCow", @"_vue4rendercow._tcp.",
                       @"VXI-11 TCP/IP Instrument Protocol", @"_vxi-11._tcp.",
                       @"World Wide Web Distributed Authoring and Versioning (WebDAV)", @"_webdav._tcp.",
                       @"WebDAV over SSL/TLS", @"_webdavs._tcp.",
                       @"Whamb", @"_whamb._tcp.",
                       @"Wired Server", @"_wired._tcp.",
                       @"WiTap Sample Game Protocol", @"_witap._tcp.",
                       @"Workgroup Server Discovery", @"_wkgrpsvr._tcp.",
                       @"Workgroup Manager", @"_workstation._tcp.",
                       @"Roku Cascade Wormhole Protocol", @"_wormhole._tcp.",
                       @"Novell collaboration workgroup", @"_workgroup._tcp.",
                       @"Web Services", @"_ws._tcp.",
                       @"Wyatt Technology Corporation HELEOS", @"_wtc-heleos._tcp.",
                       @"Wyatt Technology Corporation QELS", @"_wtc-qels._tcp.",
                       @"Wyatt Technology Corporation Optilab rEX", @"_wtc-rex._tcp.",
                       @"Wyatt Technology Corporation ViscoStar", @"_wtc-viscostar._tcp.",
                       @"Wyatt Technology Corporation DynaPro Plate Reader", @"_wtc-wpr._tcp.",
                       @"PictureSharing sample code", @"_wwdcpic._tcp.",
                       @"x-plane9", @"_x-plane9._tcp.",
                       @"Xcode Distributed Compiler", @"_xcodedistcc._tcp.",
                       @"xGate Remote Management Interface", @"_xgate-rmi._tcp.",
                       @"Xgrid", @"_xgrid._tcp.",
                       @"XMMS2 IPC Protocol", @"_xmms2._tcp.",
                       @"Xperientia Mobile Protocol", @"_xmp._tcp.",
                       @"XMPP Client Connection", @"_xmpp-client._tcp.",
                       @"XMPP Server Connection", @"_xmpp-server._tcp.",
                       @"Xsan Client", @"_xsanclient._tcp.",
                       @"Xsan Server", @"_xsanserver._tcp.",
                       @"Xsan System", @"_xsansystem._tcp.",
                       @"XServe Raid", @"_xserveraid._tcp.",
                       @"Xserve RAID Synchronization", @"_xsync._tcp.",
                       @"xTime License", @"_xtimelicence._tcp.",
                       @"xTime Project", @"_xtshapro._tcp.",
                       @"XUL (XML User Interface Language) transported over HTTP", @"_xul-http._tcp.",
                       @"Yakumo iPhone OS Device Control Protocol", @"_yakumo._tcp.",
                       @"Big Bang Backgammon", @"_bigbangbackgammon._tcp.",
                       @"Big Bang Checkers", @"_bigbangcheckers._tcp.",
                       @"ClipboardSharing", @"_clipboardsharing._tcp.",
                       @"InterBase Database Remote Protocol", @"_gds_db._tcp.",
                       @"Net Monitor Server", @"_netmonitorserver._tcp.",
                       @"OLPC Presence", @"_presence_olpc._tcp.",
                       @"Pop-Pop", @"_pop_2_ambrosia._tcp.",
                       @"ProfCast", @"_profCastLicense._tcp.",
                       @"World Book Encyclopedia", @"_WorldBook2004ST._tcp.",
                       nil
                       ];
  
  return self;
}

-(NSString*)nameForService:(NSNetService*)service {
  NSString *s = [self.serviceNames objectForKey:[service type]];
  if (s) return s;
  return [service type];
}


-(NSString*)hostnameForService:(NSNetService*)service {
  if ([service hostName])
    return [service hostName];
  struct sockaddr_in* sock = (struct sockaddr_in*)[((NSData*)[[service addresses] objectAtIndex:0]) bytes];
  return [NSString stringWithFormat:@"%s", inet_ntoa(sock->sin_addr)];
}

@end
